# config/slurm/config.yaml
cluster: "sbatch -p {cluster.queue} --time={cluster.time} --nodes=1 --cpus-per-task={cluster.cores} --mem={cluster.mem} -J {cluster.jobname} -o {cluster.outfile} -e {cluster.errfile}"
cluster-config: "config/cluster.json"
